//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:43:48 PM PST 
//


package com.github.rahulsom.jhk.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ActivitySummary")
public class ActivitySummary {

    @XmlAttribute(name = "dateComponents")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String dateComponents;
    @XmlAttribute(name = "activeEnergyBurned")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activeEnergyBurned;
    @XmlAttribute(name = "activeEnergyBurnedGoal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activeEnergyBurnedGoal;
    @XmlAttribute(name = "activeEnergyBurnedUnit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String activeEnergyBurnedUnit;
    @XmlAttribute(name = "appleExerciseTime")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appleExerciseTime;
    @XmlAttribute(name = "appleExerciseTimeGoal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appleExerciseTimeGoal;
    @XmlAttribute(name = "appleStandHours")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appleStandHours;
    @XmlAttribute(name = "appleStandHoursGoal")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String appleStandHoursGoal;

    /**
     * Gets the value of the dateComponents property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateComponents() {
        return dateComponents;
    }

    /**
     * Sets the value of the dateComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateComponents(String value) {
        this.dateComponents = value;
    }

    /**
     * Gets the value of the activeEnergyBurned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveEnergyBurned() {
        return activeEnergyBurned;
    }

    /**
     * Sets the value of the activeEnergyBurned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveEnergyBurned(String value) {
        this.activeEnergyBurned = value;
    }

    /**
     * Gets the value of the activeEnergyBurnedGoal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveEnergyBurnedGoal() {
        return activeEnergyBurnedGoal;
    }

    /**
     * Sets the value of the activeEnergyBurnedGoal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveEnergyBurnedGoal(String value) {
        this.activeEnergyBurnedGoal = value;
    }

    /**
     * Gets the value of the activeEnergyBurnedUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveEnergyBurnedUnit() {
        return activeEnergyBurnedUnit;
    }

    /**
     * Sets the value of the activeEnergyBurnedUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveEnergyBurnedUnit(String value) {
        this.activeEnergyBurnedUnit = value;
    }

    /**
     * Gets the value of the appleExerciseTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppleExerciseTime() {
        return appleExerciseTime;
    }

    /**
     * Sets the value of the appleExerciseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppleExerciseTime(String value) {
        this.appleExerciseTime = value;
    }

    /**
     * Gets the value of the appleExerciseTimeGoal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppleExerciseTimeGoal() {
        return appleExerciseTimeGoal;
    }

    /**
     * Sets the value of the appleExerciseTimeGoal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppleExerciseTimeGoal(String value) {
        this.appleExerciseTimeGoal = value;
    }

    /**
     * Gets the value of the appleStandHours property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppleStandHours() {
        return appleStandHours;
    }

    /**
     * Sets the value of the appleStandHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppleStandHours(String value) {
        this.appleStandHours = value;
    }

    /**
     * Gets the value of the appleStandHoursGoal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppleStandHoursGoal() {
        return appleStandHoursGoal;
    }

    /**
     * Sets the value of the appleStandHoursGoal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppleStandHoursGoal(String value) {
        this.appleStandHoursGoal = value;
    }

}
