//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:43:48 PM PST 
//


package com.github.rahulsom.jhk.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Me")
public class Me {

    @XmlAttribute(name = "HKCharacteristicTypeIdentifierDateOfBirth", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hkCharacteristicTypeIdentifierDateOfBirth;
    @XmlAttribute(name = "HKCharacteristicTypeIdentifierBiologicalSex", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hkCharacteristicTypeIdentifierBiologicalSex;
    @XmlAttribute(name = "HKCharacteristicTypeIdentifierBloodType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hkCharacteristicTypeIdentifierBloodType;
    @XmlAttribute(name = "HKCharacteristicTypeIdentifierFitzpatrickSkinType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String hkCharacteristicTypeIdentifierFitzpatrickSkinType;

    /**
     * Gets the value of the hkCharacteristicTypeIdentifierDateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHKCharacteristicTypeIdentifierDateOfBirth() {
        return hkCharacteristicTypeIdentifierDateOfBirth;
    }

    /**
     * Sets the value of the hkCharacteristicTypeIdentifierDateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHKCharacteristicTypeIdentifierDateOfBirth(String value) {
        this.hkCharacteristicTypeIdentifierDateOfBirth = value;
    }

    /**
     * Gets the value of the hkCharacteristicTypeIdentifierBiologicalSex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHKCharacteristicTypeIdentifierBiologicalSex() {
        return hkCharacteristicTypeIdentifierBiologicalSex;
    }

    /**
     * Sets the value of the hkCharacteristicTypeIdentifierBiologicalSex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHKCharacteristicTypeIdentifierBiologicalSex(String value) {
        this.hkCharacteristicTypeIdentifierBiologicalSex = value;
    }

    /**
     * Gets the value of the hkCharacteristicTypeIdentifierBloodType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHKCharacteristicTypeIdentifierBloodType() {
        return hkCharacteristicTypeIdentifierBloodType;
    }

    /**
     * Sets the value of the hkCharacteristicTypeIdentifierBloodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHKCharacteristicTypeIdentifierBloodType(String value) {
        this.hkCharacteristicTypeIdentifierBloodType = value;
    }

    /**
     * Gets the value of the hkCharacteristicTypeIdentifierFitzpatrickSkinType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHKCharacteristicTypeIdentifierFitzpatrickSkinType() {
        return hkCharacteristicTypeIdentifierFitzpatrickSkinType;
    }

    /**
     * Sets the value of the hkCharacteristicTypeIdentifierFitzpatrickSkinType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHKCharacteristicTypeIdentifierFitzpatrickSkinType(String value) {
        this.hkCharacteristicTypeIdentifierFitzpatrickSkinType = value;
    }

}
