//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:43:48 PM PST 
//


package com.github.rahulsom.jhk.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.rahulsom.jhk.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.rahulsom.jhk.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExportDate }
     * 
     */
    public ExportDate createExportDate() {
        return new ExportDate();
    }

    /**
     * Create an instance of {@link HealthData }
     * 
     */
    public HealthData createHealthData() {
        return new HealthData();
    }

    /**
     * Create an instance of {@link Me }
     * 
     */
    public Me createMe() {
        return new Me();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link Correlation }
     * 
     */
    public Correlation createCorrelation() {
        return new Correlation();
    }

    /**
     * Create an instance of {@link Workout }
     * 
     */
    public Workout createWorkout() {
        return new Workout();
    }

    /**
     * Create an instance of {@link ActivitySummary }
     * 
     */
    public ActivitySummary createActivitySummary() {
        return new ActivitySummary();
    }

    /**
     * Create an instance of {@link ClinicalRecord }
     * 
     */
    public ClinicalRecord createClinicalRecord() {
        return new ClinicalRecord();
    }

    /**
     * Create an instance of {@link MetadataEntry }
     * 
     */
    public MetadataEntry createMetadataEntry() {
        return new MetadataEntry();
    }

    /**
     * Create an instance of {@link HeartRateVariabilityMetadataList }
     * 
     */
    public HeartRateVariabilityMetadataList createHeartRateVariabilityMetadataList() {
        return new HeartRateVariabilityMetadataList();
    }

    /**
     * Create an instance of {@link InstantaneousBeatsPerMinute }
     * 
     */
    public InstantaneousBeatsPerMinute createInstantaneousBeatsPerMinute() {
        return new InstantaneousBeatsPerMinute();
    }

    /**
     * Create an instance of {@link WorkoutRoute }
     * 
     */
    public WorkoutRoute createWorkoutRoute() {
        return new WorkoutRoute();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link WorkoutEvent }
     * 
     */
    public WorkoutEvent createWorkoutEvent() {
        return new WorkoutEvent();
    }

}
