//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.11 at 08:43:48 PM PST 
//


package com.github.rahulsom.jhk.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataEntryOrWorkoutEventOrWorkoutRoute"
})
@XmlRootElement(name = "Workout")
public class Workout {

    @XmlAttribute(name = "workoutActivityType", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String workoutActivityType;
    @XmlAttribute(name = "duration")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String duration;
    @XmlAttribute(name = "durationUnit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String durationUnit;
    @XmlAttribute(name = "totalDistance")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String totalDistance;
    @XmlAttribute(name = "totalDistanceUnit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String totalDistanceUnit;
    @XmlAttribute(name = "totalEnergyBurned")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String totalEnergyBurned;
    @XmlAttribute(name = "totalEnergyBurnedUnit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String totalEnergyBurnedUnit;
    @XmlAttribute(name = "sourceName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sourceName;
    @XmlAttribute(name = "sourceVersion")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sourceVersion;
    @XmlAttribute(name = "device")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String device;
    @XmlAttribute(name = "creationDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String creationDate;
    @XmlAttribute(name = "startDate", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String startDate;
    @XmlAttribute(name = "endDate", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String endDate;
    @XmlElements({
        @XmlElement(name = "MetadataEntry", type = MetadataEntry.class),
        @XmlElement(name = "WorkoutEvent", type = WorkoutEvent.class),
        @XmlElement(name = "WorkoutRoute", type = WorkoutRoute.class)
    })
    protected List<Object> metadataEntryOrWorkoutEventOrWorkoutRoute;

    /**
     * Gets the value of the workoutActivityType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWorkoutActivityType() {
        return workoutActivityType;
    }

    /**
     * Sets the value of the workoutActivityType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWorkoutActivityType(String value) {
        this.workoutActivityType = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the durationUnit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDurationUnit() {
        return durationUnit;
    }

    /**
     * Sets the value of the durationUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDurationUnit(String value) {
        this.durationUnit = value;
    }

    /**
     * Gets the value of the totalDistance property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTotalDistance() {
        return totalDistance;
    }

    /**
     * Sets the value of the totalDistance property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTotalDistance(String value) {
        this.totalDistance = value;
    }

    /**
     * Gets the value of the totalDistanceUnit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTotalDistanceUnit() {
        return totalDistanceUnit;
    }

    /**
     * Sets the value of the totalDistanceUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTotalDistanceUnit(String value) {
        this.totalDistanceUnit = value;
    }

    /**
     * Gets the value of the totalEnergyBurned property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTotalEnergyBurned() {
        return totalEnergyBurned;
    }

    /**
     * Sets the value of the totalEnergyBurned property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTotalEnergyBurned(String value) {
        this.totalEnergyBurned = value;
    }

    /**
     * Gets the value of the totalEnergyBurnedUnit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTotalEnergyBurnedUnit() {
        return totalEnergyBurnedUnit;
    }

    /**
     * Sets the value of the totalEnergyBurnedUnit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTotalEnergyBurnedUnit(String value) {
        this.totalEnergyBurnedUnit = value;
    }

    /**
     * Gets the value of the sourceName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSourceName(String value) {
        this.sourceName = value;
    }

    /**
     * Gets the value of the sourceVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSourceVersion() {
        return sourceVersion;
    }

    /**
     * Sets the value of the sourceVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSourceVersion(String value) {
        this.sourceVersion = value;
    }

    /**
     * Gets the value of the device property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDevice(String value) {
        this.device = value;
    }

    /**
     * Gets the value of the creationDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreationDate(String value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the metadataEntryOrWorkoutEventOrWorkoutRoute property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataEntryOrWorkoutEventOrWorkoutRoute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataEntryOrWorkoutEventOrWorkoutRoute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataEntry }
     * {@link WorkoutEvent }
     * {@link WorkoutRoute }
     *
     *
     */
    public List<Object> getMetadataEntryOrWorkoutEventOrWorkoutRoute() {
        if (metadataEntryOrWorkoutEventOrWorkoutRoute == null) {
            metadataEntryOrWorkoutEventOrWorkoutRoute = new ArrayList<Object>();
        }
        return this.metadataEntryOrWorkoutEventOrWorkoutRoute;
    }

}
